### ISSUE TITLE
Access Violation in TUPopupMenu

### ISSUE THREAD

**Issue by zizzo81** [tonghoangvu/UniversalCL#33]
An empty line in TUPopupMenu.ItemsData will cause an Access Violation since in UCL.TUPopupMenu line 252 you have:
```
      Item.SymbolChar := ItemsData[i][1];
```

I suggest changing this to:
```
      Item.SymbolChar := Copy(ItemsData[i] + #0, 1, 1)[1];
      if (Item.SymbolChar = SeparatorChar) then
        Item.SymbolChar := #0;
```

This will make the whole thing fallback to no icon.

The added line is because I have tryed to add 5 menu items 4 of them have icon, the last one doesn't and you're drawing a #124 in place.

**Comment by ghost** [comment]
TUPopupMenu component has been rewritten and the problem is gone.
