### ISSUE TITLE
The TComboBox control does not see unselected items in Dark mode

### ISSUE THREAD

**Issue by laoqiuqiu** [tonghoangvu/UniversalCL#35]
![剪贴板图片](https://user-images.githubusercontent.com/16145623/69487261-93be7200-0e91-11ea-98e3-786e564eddcb.png)

The TComboBox control does not see unselected items in Dark mode

**Comment by ghost** [comment]
I have found the cause. The Font.Color property of those Combobox does not work when setting to clBlack. In the dark theme, it still displays white.
I tried changing that property to clWindowText, and it worked perfectly. I just updated that fix in the last commit.
