### ISSUE TITLE
TUItemButton raises exception on ShowDetail or ShowText set to false.

### ISSUE THREAD

**Issue by vhanla** [tonghoangvu/UniversalCL#36]
If TUItemButton ShowDetail or ShowText properties are set to false in order to hide them, whichever of them, the application will raise exception error.

`class EReadError with message 'Property ShowDetail does not exist'.`

`Project MyApp.exe raise exception class EReadError with message 'Error reading UItemButton1.ShowDetail does not exist'.`

**Comment by ghost** [comment]
I removed the ShowABC property from TUItemButton on the last commit.
Instead, use the new property ObjectsVisible.
