### ISSUE TITLE
Crash whenever calling TIntAni.OnDone

### ISSUE THREAD

**Issue by zizzo81** [tonghoangvu/UniversalCL#7]
Just downloaded your components, installed them and compiled your demo.
Clicked on the gear icon in the left TUPanel and got an access violation exception. Since read of address is nil this was easy to track down.

Last line of TIntAni.Execute has a synchronized call to DoneControl which simply calls the OnDone property. No one ever sets this so it's nil.

I suggest to make this change:

```
procedure TIntAni.DoneControl;
begin
//  OnDone;  // don't call events like this
  if @FOnDone <> nil then
    FOnDone()
end;
```
Strangely this isn't enough to solve the problems, a subsequent call has this initialized and crashes.

I initialize this to nil in the thread constructor.
Changed:
`      property OnDone: TProc read FOnDone write FOnDone;
`To:
`      property OnDone: TProc read FOnDone write SetOnDone;`

So I was able to set a breakpoint in the setter to understand who the hell was setting this, since a search in the code didn't help. Guess what: setter gets never called.

There must be some in-memory mashup.

**Comment by ghost** [comment]
Thanks for the feedback.
On the first issue, I can easily recreate and fix it.
However, with the next problem you mentioned, I tried creating setter for FOnDone, and setter is still called normally. No exceptions are thrown.
I want to know how you set up TIntAni.OnDone, I think the problem is there.
This is my way to set OnDone
```
Ani.OnDone := procedure begin ... end;
```

**Comment by zizzo81** [comment]
I simply don't. It's you original demo source and  the only changes I've done to the components sources are these mentioned above.

**Comment by ghost** [comment]
I will try again. Besides, can you tell me which version of Delphi and OS you are using?

**Comment by zizzo81** [comment]
Being `FOnDone` a `reference to procedure` you need to use `Assigned` to check for its validity.

```
procedure TIntAni.DoneControl;
begin
  if Assigned(FOnDone) then
    FOnDone()
end;
```

This works.

**Comment by ghost** [comment]
Oh, that's exactly what I did. I uploaded the modified version.
Thanks again.
