### ISSUE TITLE
Small glitch while resizing components inside TUPanel

### ISSUE THREAD

**Issue by zizzo81** [tonghoangvu/UniversalCL#8]
There's a small drawing glitch when resizing components on the right TUPanel.
I tried it on 3 different computers 2 running Windows 10 1809, the last one has 1903 and the glitch is there.

![glytch](https://user-images.githubusercontent.com/17153683/59923173-10f14100-9433-11e9-8d64-16977ff140c3.png)

Being a minor glitch I'm not going to hunt this down.

**Comment by ghost** [comment]
I just uploaded a patch for this problem. It seems that TUEdit has not been repaint correctly when resizing
